# -*- coding: utf-8 -*-
"""
data/vocab.py
База слов, фраз и разговорного/сленгового испанского (регистр Испании,
т.к. ориентируемся на разговорный вариант, а не латиноамериканский).

Формат каждой записи:
(испанское слово/фраза, перевод, категория, уровень, пример_на_испанском)

категории: 'verb_inf', 'noun', 'adjective', 'phrase', 'slang', 'adverb'
уровни: 'A2', 'B1', 'B2'

Это стартовый набор (~350 единиц). Список сделан расширяемым: чтобы
добавить новые слова, просто дописывайте кортежи в один из списков ниже
и перезапустите seed_database() — дубликаты (по паре испанский+перевод)
игнорируются на уровне базы (UNIQUE constraint).
"""

VERBS_INF = [
    ("ser", "быть (постоянный признак)", "verb_inf", "A2", "Soy de Rusia."),
    ("estar", "быть (состояние/место)", "verb_inf", "A2", "Estoy en casa."),
    ("tener", "иметь", "verb_inf", "A2", "Tengo dos hermanos."),
    ("hacer", "делать", "verb_inf", "A2", "¿Qué haces ahora mismo?"),
    ("ir", "идти/ехать", "verb_inf", "A2", "Voy al trabajo."),
    ("poder", "мочь", "verb_inf", "A2", "¿Puedes ayudarme?"),
    ("decir", "говорить/сказать", "verb_inf", "A2", "Dime la verdad."),
    ("ver", "видеть", "verb_inf", "A2", "No veo nada."),
    ("dar", "давать", "verb_inf", "A2", "Dame un momento."),
    ("saber", "знать (факт)", "verb_inf", "A2", "No sé la respuesta."),
    ("querer", "хотеть/любить", "verb_inf", "A2", "Quiero un café."),
    ("llegar", "прибывать", "verb_inf", "A2", "Llego a las nueve."),
    ("pasar", "проходить/происходить", "verb_inf", "A2", "¿Qué pasa?"),
    ("deber", "быть должным", "verb_inf", "A2", "Debo terminar esto hoy."),
    ("poner", "класть/ставить", "verb_inf", "A2", "Pon la mesa, por favor."),
    ("parecer", "казаться", "verb_inf", "B1", "Me parece bien."),
    ("quedar", "оставаться/встречаться", "verb_inf", "B1", "Quedamos a las ocho."),
    ("creer", "верить/думать", "verb_inf", "A2", "Creo que sí."),
    ("hablar", "говорить", "verb_inf", "A2", "Hablo español un poco."),
    ("llevar", "нести/носить", "verb_inf", "A2", "Llevo dos años aquí."),
    ("dejar", "оставлять/позволять", "verb_inf", "A2", "Déjame en paz."),
    ("seguir", "продолжать/следовать", "verb_inf", "A2", "Sigue recto."),
    ("encontrar", "находить", "verb_inf", "A2", "No encuentro las llaves."),
    ("llamar", "звать/звонить", "verb_inf", "A2", "Te llamo luego."),
    ("venir", "приходить", "verb_inf", "A2", "Vengo enseguida."),
    ("pensar", "думать", "verb_inf", "A2", "Pienso que tienes razón."),
    ("salir", "выходить", "verb_inf", "A2", "Salgo del trabajo a las seis."),
    ("volver", "возвращаться", "verb_inf", "A2", "Vuelvo mañana."),
    ("tomar", "брать/пить", "verb_inf", "A2", "Voy a tomar un café."),
    ("conocer", "знать (человека/место)", "verb_inf", "A2", "Conozco a tu hermana."),
    ("vivir", "жить", "verb_inf", "A2", "Vivo en Valencia."),
    ("sentir", "чувствовать", "verb_inf", "A2", "Lo siento mucho."),
    ("mirar", "смотреть", "verb_inf", "A2", "Mira esto."),
    ("contar", "считать/рассказывать", "verb_inf", "B1", "Cuéntame qué pasó."),
    ("empezar", "начинать", "verb_inf", "A2", "Empiezo a trabajar a las nueve."),
    ("esperar", "ждать/надеяться", "verb_inf", "A2", "Espero que todo vaya bien."),
    ("buscar", "искать", "verb_inf", "A2", "Busco trabajo."),
    ("entender", "понимать", "verb_inf", "A2", "No entiendo nada."),
    ("pedir", "просить/заказывать", "verb_inf", "A2", "Voy a pedir la cuenta."),
    ("recordar", "помнить/напоминать", "verb_inf", "B1", "No recuerdo su nombre."),
    ("trabajar", "работать", "verb_inf", "A2", "Trabajo en ventas."),
    ("escribir", "писать", "verb_inf", "A2", "Escribo un correo."),
    ("perder", "терять", "verb_inf", "A2", "No quiero perder el tren."),
    ("aceptar", "принимать/соглашаться", "verb_inf", "B1", "Acepto tu propuesta."),
    ("cambiar", "менять", "verb_inf", "A2", "Quiero cambiar de trabajo."),
    ("intentar", "пытаться", "verb_inf", "B1", "Voy a intentarlo."),
    ("mostrar", "показывать", "verb_inf", "B1", "Muéstrame el documento."),
    ("necesitar", "нуждаться", "verb_inf", "A2", "Necesito más tiempo."),
    ("comprar", "покупать", "verb_inf", "A2", "Voy a comprar pan."),
    ("terminar", "заканчивать", "verb_inf", "A2", "Termino a las siete."),
    ("permitir", "разрешать", "verb_inf", "B1", "No me permiten fumar aquí."),
]

NOUNS = [
    ("la familia", "семья", "noun", "A2", "Mi familia es grande."),
    ("el hermano / la hermana", "брат / сестра", "noun", "A2", "Tengo un hermano."),
    ("el amigo / la amiga", "друг / подруга", "noun", "A2", "Es mi mejor amigo."),
    ("el trabajo", "работа", "noun", "A2", "Me gusta mi trabajo."),
    ("la casa", "дом", "noun", "A2", "Mi casa es pequeña."),
    ("la ciudad", "город", "noun", "A2", "Valencia es una ciudad bonita."),
    ("el coche", "машина", "noun", "A2", "Mi coche es nuevo."),
    ("el dinero", "деньги", "noun", "A2", "No tengo dinero."),
    ("el tiempo", "время / погода", "noun", "A2", "No tengo tiempo."),
    ("la comida", "еда", "noun", "A2", "La comida está lista."),
    ("el agua", "вода", "noun", "A2", "Quiero un vaso de agua."),
    ("la cerveza", "пиво", "noun", "A2", "Una cerveza, por favor."),
    ("el vino", "вино", "noun", "A2", "Me gusta el vino tinto."),
    ("la calle", "улица", "noun", "A2", "Vivo en esta calle."),
    ("el barrio", "район (города)", "noun", "B1", "Mi barrio es tranquilo."),
    ("la reunión", "встреча/совещание", "noun", "B1", "Tengo una reunión a las diez."),
    ("el cliente", "клиент", "noun", "A2", "El cliente está contento."),
    ("la empresa", "компания/фирма", "noun", "A2", "Trabajo para una empresa grande."),
    ("el jefe / la jefa", "начальник / начальница", "noun", "A2", "Mi jefe es exigente."),
    ("el sueldo", "зарплата", "noun", "B1", "El sueldo es bajo."),
    ("la factura", "счёт/инвойс", "noun", "B1", "Tengo que pagar la factura."),
    ("el contrato", "контракт/договор", "noun", "B1", "Firmamos el contrato."),
    ("la playa", "пляж", "noun", "A2", "Vamos a la playa."),
    ("el sol", "солнце", "noun", "A2", "Hace mucho sol."),
    ("la lluvia", "дождь", "noun", "A2", "Está cayendo lluvia."),
    ("el mercado", "рынок", "noun", "A2", "Compro fruta en el mercado."),
    ("la tienda", "магазин", "noun", "A2", "La tienda cierra a las nueve."),
    ("el móvil", "мобильный телефон", "noun", "A2", "Se me ha roto el móvil."),
    ("el ordenador", "компьютер", "noun", "A2", "Trabajo con el ordenador."),
    ("la salud", "здоровье", "noun", "B1", "La salud es lo primero."),
    ("la vida", "жизнь", "noun", "A2", "Así es la vida."),
    ("el problema", "проблема", "noun", "A2", "No hay problema."),
    ("la solución", "решение", "noun", "B1", "Buscamos una solución."),
    ("la oportunidad", "возможность", "noun", "B1", "Es una buena oportunidad."),
    ("el favor", "услуга/одолжение", "noun", "A2", "¿Me haces un favor?"),
    ("la costumbre", "привычка/обычай", "noun", "B1", "Es una costumbre española."),
    ("la verdad", "правда", "noun", "A2", "Dime la verdad."),
    ("la mentira", "ложь", "noun", "A2", "Eso es mentira."),
    ("el recuerdo", "воспоминание", "noun", "B1", "Tengo buenos recuerdos de aquí."),
    ("la suerte", "удача", "noun", "A2", "¡Buena suerte!"),
]

ADJECTIVES = [
    ("cansado/a", "усталый", "adjective", "A2", "Estoy muy cansado hoy."),
    ("ocupado/a", "занятый", "adjective", "A2", "Estoy ocupado ahora."),
    ("contento/a", "довольный", "adjective", "A2", "Estoy contento con el resultado."),
    ("enfadado/a", "злой/сердитый", "adjective", "A2", "Está enfadado conmigo."),
    ("tranquilo/a", "спокойный", "adjective", "A2", "Es una persona tranquila."),
    ("nervioso/a", "нервный", "adjective", "A2", "Estoy nervioso por la reunión."),
    ("caro/a", "дорогой", "adjective", "A2", "Este restaurante es caro."),
    ("barato/a", "дешёвый", "adjective", "A2", "Busco algo más barato."),
    ("rápido/a", "быстрый", "adjective", "A2", "Necesito una respuesta rápida."),
    ("lento/a", "медленный", "adjective", "A2", "El internet va muy lento."),
    ("fácil", "лёгкий/простой", "adjective", "A2", "Este examen es fácil."),
    ("difícil", "сложный/трудный", "adjective", "A2", "Es un cliente difícil."),
    ("importante", "важный", "adjective", "A2", "Es muy importante para mí."),
    ("interesante", "интересный", "adjective", "A2", "Un proyecto interesante."),
    ("aburrido/a", "скучный", "adjective", "A2", "La reunión fue aburrida."),
    ("gracioso/a", "смешной/забавный", "adjective", "B1", "Es muy gracioso."),
    ("amable", "добрый/вежливый", "adjective", "A2", "El vendedor fue muy amable."),
    ("simpático/a", "приятный (о человеке)", "adjective", "A2", "Es muy simpático."),
    ("raro/a", "странный", "adjective", "A2", "Qué raro, ¿no?"),
    ("seguro/a", "уверенный/безопасный", "adjective", "A2", "No estoy seguro."),
    ("listo/a", "умный / готовый (в зависимости от контекста)", "adjective", "B1", "Es muy listo."),
    ("tonto/a", "глупый", "adjective", "A2", "No seas tonto."),
    ("gordo/a", "толстый", "adjective", "A2", "El gato está muy gordo."),
    ("delgado/a", "худой", "adjective", "A2", "Está más delgado que antes."),
    ("guapo/a", "красивый", "adjective", "A2", "Qué guapa estás hoy."),
    ("fuerte", "сильный", "adjective", "A2", "Es un café muy fuerte."),
    ("débil", "слабый", "adjective", "B1", "Me siento un poco débil."),
    ("libre", "свободный", "adjective", "A2", "¿Estás libre esta tarde?"),
    ("harto/a", "уставший от чего-то / сытый по горло", "adjective", "B1", "Estoy harto de este trabajo."),
    ("agotado/a", "измождённый/вымотанный", "adjective", "B1", "Llegué agotado a casa."),
]

PHRASES = [
    ("¿Qué tal?", "Как дела?", "phrase", "A2", "¡Hola! ¿Qué tal todo?"),
    ("¿Qué pasa?", "Что происходит? / Как дела?", "phrase", "A2", "¿Qué pasa contigo?"),
    ("No pasa nada", "Ничего страшного", "phrase", "A2", "No pasa nada, tranquilo."),
    ("Vale", "Ладно/окей", "phrase", "A2", "Vale, nos vemos mañana."),
    ("Claro que sí", "Конечно да", "phrase", "A2", "¿Puedes ayudarme? Claro que sí."),
    ("Ni idea", "Понятия не имею", "phrase", "A2", "¿Dónde está? Ni idea."),
    ("Depende", "Зависит (от обстоятельств)", "phrase", "A2", "¿Vienes? Depende del tiempo."),
    ("Qué va", "Да ладно / вовсе нет", "phrase", "B1", "¿Estás enfadado? Qué va."),
    ("Menos mal", "Слава богу / хорошо, что", "phrase", "B1", "Menos mal que llegaste a tiempo."),
    ("Vamos a ver", "Посмотрим", "phrase", "A2", "Vamos a ver qué pasa."),
    ("A ver", "Ну-ка / посмотрим", "phrase", "A2", "A ver, enséñame el móvil."),
    ("Por si acaso", "На всякий случай", "phrase", "B1", "Llévate el paraguas por si acaso."),
    ("De momento", "Пока что / на данный момент", "phrase", "B1", "De momento todo va bien."),
    ("En seguida", "Сейчас же / немедленно", "phrase", "A2", "Voy en seguida."),
    ("Poco a poco", "Постепенно / понемногу", "phrase", "A2", "Lo estoy aprendiendo poco a poco."),
    ("Dar igual", "Быть всё равно", "phrase", "B1", "Me da igual la hora."),
    ("Echar de menos", "Скучать по кому-то/чему-то", "phrase", "B1", "Echo de menos mi país."),
    ("Tener ganas de", "Хотеть чего-то (иметь желание)", "phrase", "B1", "Tengo ganas de viajar."),
    ("Estar harto/a de", "Быть сытым по горло чем-то", "phrase", "B1", "Estoy harto de esperar."),
    ("Darse cuenta de", "Осознать/понять", "phrase", "B1", "Me di cuenta del error."),
    ("Hacer falta", "Быть нужным/необходимым", "phrase", "B1", "Hace falta más tiempo."),
    ("Tener razón", "Быть правым", "phrase", "A2", "Tienes toda la razón."),
    ("Meter la pata", "Облажаться / сделать промах", "phrase", "B1", "Metí la pata en la reunión."),
    ("Costar un ojo de la cara", "Стоить очень дорого", "phrase", "B2", "Este piso cuesta un ojo de la cara."),
    ("Ponerse las pilas", "Взяться за дело / собраться", "phrase", "B1", "Tienes que ponerte las pilas."),
    ("No tener pelos en la lengua", "Говорить прямо/без обиняков", "phrase", "B2", "No tiene pelos en la lengua."),
    ("Estar en las nubes", "Витать в облаках", "phrase", "B1", "Hoy estás en las nubes."),
    ("Tomar el pelo", "Разыгрывать/дурачить кого-то", "phrase", "B1", "¿Me estás tomando el pelo?"),
    ("Ser pan comido", "Быть очень лёгким делом", "phrase", "B2", "El examen fue pan comido."),
    ("Estar como una cabra", "Быть немного сумасшедшим (в шутку)", "phrase", "B2", "Está como una cabra, pero le quiero."),
]

# Разговорный сленг (регистр Испании — что реально услышишь в Валенсии/по стране)
SLANG = [
    ("tío / tía", "чувак / чувиха (обращение к другу)", "slang", "A2", "¡Tío, qué dices!"),
    ("guay", "круто/классно", "slang", "A2", "Qué guay tu casa nueva."),
    ("mola", "круто (нравится)", "slang", "A2", "Me mola mucho esta canción."),
    ("flipar", "офигевать/поражаться", "slang", "B1", "Flipo con este precio."),
    ("currar", "пахать/работать", "slang", "B1", "Hoy he currado mucho."),
    ("el curro", "работа (разг.)", "slang", "B1", "Voy al curro."),
    ("la pasta", "бабки/деньги", "slang", "B1", "No tengo pasta ahora mismo."),
    ("el finde", "выходные", "slang", "A2", "¿Qué haces este finde?"),
    ("el móvil se ha petado", "телефон сломался/завис", "slang", "B1", "Se me ha petado el móvil."),
    ("estar flipando", "быть в шоке/офигевать", "slang", "B1", "Estoy flipando con la noticia."),
    ("qué fuerte", "офигеть/вот это да", "slang", "A2", "¿En serio? ¡Qué fuerte!"),
    ("chungo/a", "плохой/сложный/подозрительный", "slang", "B1", "Este barrio está un poco chungo de noche."),
    ("majo/a", "милый/приятный человек", "slang", "A2", "Tu vecino es muy majo."),
    ("qué rollo", "как скучно/что за морока", "slang", "B1", "Qué rollo de reunión."),
    ("dar corte", "стесняться/быть неловко", "slang", "B2", "Me da corte preguntar."),
    ("estar de bajón", "быть в грустном настроении", "slang", "B2", "Hoy estoy de bajón."),
    ("liarla", "устроить бардак/накосячить", "slang", "B1", "La has liado bien."),
    ("estar liado/a", "быть занятым/загруженным", "slang", "B1", "Estoy muy liado esta semana."),
    ("un rato", "какое-то время", "slang", "A2", "Espera un rato."),
    ("vacilar", "подшучивать/выпендриваться", "slang", "B2", "No me vaciles."),
    ("pillar", "поймать/понять/достать (купить)", "slang", "B1", "¿Pillas lo que digo?"),
    ("el peque / la peque", "малыш/малышка", "slang", "A2", "El peque ya duerme."),
    ("colega", "приятель/коллега (разг.)", "slang", "A2", "Es un colega del trabajo."),
    ("plan", "план/затея (в разг. смысле)", "slang", "A2", "¿Qué plan tienes hoy?"),
    ("el curro está chungo", "на работе тяжело/сложно", "slang", "B2", "Este mes el curro está chungo."),
    ("estar a tope", "быть очень занятым/загруженным по полной", "slang", "B1", "Esta semana estoy a tope."),
    ("no hay tu tía", "ничего не поделаешь (устойчивое выражение)", "slang", "B2", "Aquí no hay tu tía, hay que currar."),
    ("estar pez", "ничего не смыслить в чём-то", "slang", "B2", "Estoy pez en informática."),
    ("un movidón", "большая заварушка/суматоха", "slang", "B2", "Se montó un movidón en la fiesta."),
    ("qué chulo/a", "как круто/классно (о вещи)", "slang", "A2", "Qué chulo tu coche nuevo."),
]

ALL_LISTS = [VERBS_INF, NOUNS, ADJECTIVES, PHRASES, SLANG]


def all_words():
    """Плоский список всех записей из всех категорий."""
    result = []
    for lst in ALL_LISTS:
        result.extend(lst)
    return result
